# Index definition for Watchtower

[wt_alerts]
homePath = $SPLUNK_DB/watchtower/db
coldPath = $SPLUNK_DB/watchtower/colddb
thawedPath = $SPLUNK_DB/watchtower/thaweddb
maxTotalDataSizeMB = 5120
frozenTimePeriodInSecs = 2592000
