# Transforms for Watchtower

# Field extractions for wt_alerts
[wt_alerts_fields]
REGEX = (?<wt_alert_id>[a-f0-9\-]+)\s+(?<alert_create_time>\d+)\s+(?<alert_name>[^=]+)
FORMAT = wt_alert_id::$1 alert_create_time::$2 alert_name::$3

# KVStore lookup
[wt_alerts_reference]
collection = wt_alerts_reference
external_type = kvstore
fields_list = wt_alert_id,alert_name,alert_create_time,alert_status,sent_to_soar,soar_incident_id,soar_story_name,soar_response,retry_count,last_updated,error_message,alert_severity,alert_source,payload,rule_id,raw_event,sourcetype
